[package]
name = "toql"
version = "0.1.0"
authors = ["Roy Ganz <roy.ganz@glanis.ch>"]
edition = "2018"

[dependencies]
toql_core = { path = "toql_core", version = "0.1.0" }
toql_mysql = { path = "toql_mysql", version = "0.1.0", optional = true }
toql_rocket = { path = "toql_rocket", version = "0.1.0", optional = true }
toql_derive = { path = "toql_derive", version = "0.1.0" }

log = "0.4"

[workspace]
members =  [
    "toql_core",
    "toql_mysql",
    "toql_rocket",
    "toql_derive"
]

[features]
mysql = ["toql_mysql", "toql_derive/mysqldb"]
rocket_mysql = ["toql_rocket/mysqldb", "toql_derive/mysqldb", "toql_mysql"]

 
