[package]
name = "toql"
version = "0.1.2"
authors = ["Roy Ganz <roy.ganz@glanis.ch>"]
edition = "2018"
description = "The toql query language"
keywords = ["toql"]
readme = "README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/roy-ganz/toql"

[dependencies]
toql_core = { path = "toql_core", version = "0.1" }
toql_mysql = { path = "toql_mysql", version = "0.1", optional = true }
toql_rocket = { path = "toql_rocket", version = "0.1", optional = true }
toql_derive = { path = "toql_derive", version = "0.1" }

log = "0.4"

[workspace]
members =  [
    "toql_core",
    "toql_mysql",
    "toql_rocket",
    "toql_derive"
]

[features]
mysql = [ "toql_core/mysqldb", "toql_mysql", "toql_derive/mysqldb"]
rocket_mysql = ["toql_core/mysqldb","toql_core/rocketweb", "toql_rocket/mysqldb", "toql_derive/mysqldb", "toql_mysql"]

[dev-dependencies]
rocket = "0.4" 
rocket_contrib =  {version = "0.4", default-features = false, features = ["mysql_pool", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toql = { version = "0.1", path = "../toql",features= ["rocket_mysql"] }

[[example]]
name = "crud_rocket_mysql"
path = "examples/rocket_mysql/main.rs"
required-features = ["rocket_mysql"]

 
