[package]
name = "toql"
version = "0.1.0"
authors = ["roy"]
edition = "2018"

[dependencies]
pest = "2.0"
pest_derive = "2.0"
mysql = {version = "14.2.0", optional = true}

[features]
mysqldb = ["mysql"]


